name: CI
on:
  push:
#    branches: [ master, tmp ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        # sbcl32 and clisp32 don't work, clasp won't build on CI servers
        lisp: [sbcl-bin,sbcl]
        os: [windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # specify default shell explicitly to get msys instead of git-bash on windows
        shell: ${{ fromJSON('[ "bash", "msys2 {0}" ]') [ matrix.os == 'windows-latest' ] }}

    steps:
    - uses: msys2/setup-msys2@v2
      if: matrix.os == 'windows-latest'
      with:
        path-type: inherit
        msystem: MINGW64
        # set these to true if we want to install things from pacman
        release: true
        update: true
        # list all packages we want installed if using release&update true
        install: 'git base-devel unzip mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-zlib'

    - name: windows specific settings
      if: matrix.os == 'windows-latest'
      # run with pwsh so we can see its HOME, though probably could use $USERPROFILE instead
      shell: pwsh
      run: |
        git config --global core.autocrlf false
        echo "MSYSCON=defterm" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "$HOME/.roswell/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo "$HOME/.roswell/lisp/quicklisp/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo "$HOME/.roswell/bin"
        echo "ENV $Env:GITHUB_ENV"
        echo "PATH $Env:GITHUB_PATH"
        cat $Env:GITHUB_ENV
        cat $Env:GITHUB_PATH

    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: pngload

    # check out extra repos if not in QL, or version in ql is too old
    - run: mkdir -p ~/lisp/

    - name: ci-utils fork
      uses: actions/checkout@v2
      with:
        repository: 3b/ci-utils
        ref: test2
        path: ~/lisp/ci-utils

    - name: skippy fork
      uses: actions/checkout@v2
      with:
        repository: 3b/skippy
        path: ~/lisp/skippy

    - name: opticl from git
      uses: actions/checkout@v2
      with:
        repository: slyrus/opticl
        path: ~/lisp/opticl

    - name: cache .roswell
      id: cache-dot-roswell
      uses: actions/cache@v1
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-${{ hashFiles('**/*.asd') }}
        restore-keys: |
          ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-
          ${{ runner.os }}-dot-roswell-

    - name: install roswell
      # continue-on-error: true
      # always run install, since it does some global installs and setup that isn't cached
      env:
       LISP: ${{ matrix.lisp }}
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

    - name: print version/configuration info
      continue-on-error: true
      run: |
        echo "PATH=$PATH"
        echo "MSYSCON=$MSYSCON"
        echo "LOCALAPPDATA=$LOCALAPPDATA"
        ls $LOCALAPPDATA/config/common-lisp/source-registry.conf.d || true
        echo "HOME=$HOME"
        ls $HOME/.config/common-lisp/source-registry.conf.d  || true
        echo localappdata conf
        cat $LOCALAPPDATA/config/common-lisp/source-registry.conf.d/ci.conf  || true
        echo home conf
        cat $HOME/.config/common-lisp/source-registry.conf.d/ci.conf  || true
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        echo `echo $GITHUB_WORKSPACE | sed -e 's/\\\\/\//g'`
        ros -e '(format t "~a:~a on ~a~%...~%~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))'
        ros -e '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))'
        ros -e "(ql:quickload 'trivial-features)" -e '(format t "features = ~s~%" *features*)'
        which gcc
        gcc --version

    - name: update ql dist if we have one cached
      run: |
        ros -e "(ql:update-all-dists :prompt nil)"

    - name: install ci-utils
      run: |
        ros install ci-utils
        echo "$HOME/.roswell/bin" >> $GITHUB_PATH
        echo "$HOME/.roswell/bin"

    - name: clear fasl cache1
      run: |
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/ || true
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests1
      continue-on-error: true
      run: |
        run-test-forms -l pngload.test '(pngload.test:run-tests-for-ci)'

    - name: clear fasl cache2
      run: |
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests2
      continue-on-error: true
      run: |
        run-test-forms -l cffi 't'

    - name: clear fasl cache3
      run: |
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests3
      continue-on-error: true
      run: |
        run-test-forms -l cffi 't'

    - name: clear fasl cache3
      run: |
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests3
      continue-on-error: true
      run: |
        run-test-forms -l cffi 't'

    - name: clear fasl cache3
      run: |
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests3
      continue-on-error: true
      run: |
        run-test-forms -l cffi 't'

    - name: clear fasl cache3
      run: |
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests3
      continue-on-error: true
      run: |
        run-test-forms -l cffi 't'

    - name: clear fasl cache3
      run: |
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests3
      continue-on-error: true
      run: |
        run-test-forms -l cffi 't'

    - name: clear fasl cache3
      run: |
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests3
      continue-on-error: true
      run: |
        run-test-forms -l babel 't'
        run-test-forms -l cffi 't'

    - name: clear fasl cache3
      run: |
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests3
      continue-on-error: true
      run: |
        run-test-forms -l babel 't'
        run-test-forms -l cffi 't'


    - name: clear fasl cache4
      run: |
        echo "~"
        ls ~/ || true
        echo "HOME ($HOME) "
        ls $HOME/ || true
        echo "USERPROFILE ($USERPROFILE) "
        ls $USERPROFILE/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/
        
    - name: load code from clean fasl cache and run tests4
      continue-on-error: true
      run: |
        echo find setup
        find ~/ -name setup.lisp
        find $HOME/ -name setup.lisp
        find $USERPROFILE/ -name setup.lisp
        echo find sbcl
        find ~/ -name sbcl.exe
        find $HOME -name sbcl.exe
        find $USERPROFILE -name sbcl.exe
        find . -name sbcl.exe
        echo ls
        ls -lr $USERPROFILE/.roswell/impls/x86-64/windows/sbcl/2.1.11/
        $USERPROFILE/.roswell/impls/x86-64/windows/sbcl/2.1.11/bin/sbcl --load /c/users/runneradmin/.roswell/lisp/quicklisp/quicklisp/setup.lisp --eval "(ql:quickload 'cffi)"


    - name: clear fasl cache5
      run: |
        rm -rf ~/AppData/Local/cache/common-lisp/ || true
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/

    - name: test6
      continue-on-error: true
      run: |
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        $USERPROFILE/.roswell/impls/x86-64/windows/sbcl/2.1.11/bin/sbcl --load /c/users/runneradmin/.roswell/lisp/quicklisp/quicklisp/setup.lisp --eval "(ql:quickload 'cffi)"

    - name: test6
      continue-on-error: true
      run: |
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        $USERPROFILE/.roswell/impls/x86-64/windows/sbcl/2.1.11/bin/sbcl --load /c/users/runneradmin/.roswell/lisp/quicklisp/quicklisp/setup.lisp --eval "(ql:quickload 'cffi)"

    - name: test6
      continue-on-error: true
      run: |
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        $USERPROFILE/.roswell/impls/x86-64/windows/sbcl/2.1.11/bin/sbcl --load /c/users/runneradmin/.roswell/lisp/quicklisp/quicklisp/setup.lisp --eval "(ql:quickload 'cffi)"

    - name: test6
      continue-on-error: true
      run: |
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        $USERPROFILE/.roswell/impls/x86-64/windows/sbcl/2.1.11/bin/sbcl --load /c/users/runneradmin/.roswell/lisp/quicklisp/quicklisp/setup.lisp --eval "(ql:quickload 'cffi)"

    - name: test6
      continue-on-error: true
      run: |
        rm -rf $USERPROFILE/AppData/Local/cache/common-lisp/ || true
        $USERPROFILE/.roswell/impls/x86-64/windows/sbcl/2.1.11/bin/sbcl --load /c/users/runneradmin/.roswell/lisp/quicklisp/quicklisp/setup.lisp --eval "(ql:quickload 'cffi)"




